### ISSUE TITLE
图标和消息的位置没有对齐/添加图标后没有透明状态栏

### ISSUE THREAD

**Issue by liangjingkanji** [liuguangqiang/CookieBar#3]
![](https://ws1.sinaimg.cn/large/006tNc79gy1fif7f7cc1dj30u01hc3yy.jpg)

**Comment by liuguangqiang** [comment]
请问你使用的是什么设备？android什么版本呢？

**Comment by liuguangqiang** [comment]
我用nexus6p测试过是正常的

**Comment by liangjingkanji** [comment]
你布局的message有个8dp的marginTop怎么可能正常
至于透明状态栏不添加icon没问题, 添加了icon提醒框就无法覆盖状态栏了
我的是一加3T Adnroid 7.1.1

对了, 能否改成用全局上下文

**Comment by liuguangqiang** [comment]
我知道你的问题了，你可以用title，不显示message，就剧中了

**Comment by liangjingkanji** [comment]
我最关心的还是为啥加了图标就不透明了, 我再看看吧

**Comment by liuguangqiang** [comment]
你是说statusBar的沉浸式有问题？

**Comment by liuguangqiang** [comment]
![wechatimg5](https://user-images.githubusercontent.com/4328991/29203208-cfb37436-7ea1-11e7-8672-18d855ac356c.png)
我这是用一加3T 7.1.1 氧OS测试的

**Comment by liangjingkanji** [comment]
那应该是我的透明状态栏参数的问题了, 谢谢帮助了

**Comment by liuguangqiang** [comment]
没事，多谢你的comment

**Comment by liuguangqiang** [comment]
Fixed.
